depth = -6;
image_speed = 0.35;
name = "";
ghostid = "";
roomnumber = room;
spr_palette = spr_peppalette;
character = "P";
ispeppino = true;
paletteselect = 1;
player_paletteselect[0] = 1;
player_patterntexture[0] = -4;
player_paletteselect[1] = 1;
player_patterntexture[1] = -4;
player_paletteindex = 0;
player_index = 0;
pal = player_index;
scr_characterspr();
xscale = 1;
yscale = 1;
show_debug_message("I have been created!");