depth = -6;
spr_palette = spr_peppalette;
character = "P";
paletteselect = 1;
player_paletteselect[0] = 1;
player_patterntexture[0] = -4;
player_paletteselect[1] = 1;
player_patterntexture[1] = -4;
player_paletteindex = 0;
player_index = 0;
pal = player_index;
scr_characterspr();
yscale = 1;